version: '{build}'
shallow_clone: true

platform: x64

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
# CMake
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    BUILDER: cmake

matrix:
  fast_finish: false

cache:
  - dependencies\install -> makefiles\Makefile.third_party.win.mk
  - build\dependencies\install -> cmake\dependencies

before_build:
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
  - set PATH=C:\Python38-x64;%PATH%
  - tools\win\which.exe python.exe
  - python -V
  - python -m pip install virtualenv wheel six
  - tools\win\which.exe dotnet.exe
  - dotnet --info
  - set "JAVA_HOME=C:\Program Files\Java\jdk11"
  - set "PATH=C:\Program Files\Java\jdk11\bin;%PATH%"
  - java -version
  - set CMAKE_BUILD_PARALLEL_LEVEL=4
  - cmake --version
  - cmake -S. -Bbuild -DCMAKE_BUILD_TYPE:STRING=Release -DBUILD_DEPS:BOOL=ON -G "Visual Studio 16 2019"

build_script:
  - cmake --build build --config Release --target ALL_BUILD -- %MSBUILD_FLAGS%

test_script:
  - cmake --build build --config Release --target RUN_TESTS
